In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
np.random.seed(42)

n = 20000

df = pd.DataFrame({
    "amount": np.random.exponential(scale=100, size=n),
    "hour": np.random.randint(0, 24, size=n),
    "distance_from_home": np.random.exponential(scale=20, size=n),
    "failed_attempts": np.random.poisson(lam=0.3, size=n),
    "country_changed": np.random.binomial(1, 0.05, size=n)
})

In [4]:
df.head()

       amount  hour  distance_from_home  failed_attempts  country_changed
0   46.926809    21           39.953490                1                0
1  301.012143     1            5.686026                1                0
2  131.674569     3           36.401278                0                0
3   91.294255    12            3.709280                0                0
4   16.962487    12            4.415619                0                0

In [5]:
df.shape

(20000, 5)

In [6]:
fraud_probability = (
    0.01
    + 0.0005 * df["amount"]
    + 0.01 * df["distance_from_home"]
    + 0.15 * df["failed_attempts"]
    + 0.8 * df["country_changed"]
    + 0.3 * ((df["hour"] < 5).astype(int))
)

fraud_probability = np.clip(fraud_probability, 0, 0.95)

df["is_fraud"] = np.random.binomial(1, fraud_probability)

In [8]:
df["fraud_probability"] = fraud_probability

In [10]:
df.head(10)

,amount,hour,distance_from_home,failed_attempts,country_changed,is_fraud,fraud_probability
0,46.926809,21,39.953490,1,0,0,0.582998
1,301.012143,1,5.686026,1,0,0,0.667366
2,131.674569,3,36.401278,0,0,0,0.739850
3,91.294255,12,3.709280,0,0,0,0.092740
4,16.962487,12,4.415619,0,0,0,0.062637
5,16.959629,22,2.333300,0,0,0,0.041813
6,5.983877,21,38.981818,0,0,1,0.402810
7,201.123086,22,2.291490,1,0,0,0.283476
8,91.908215,16,2.972587,0,0,0,0.085680
9,123.125006,5,5.644265,0,0,0,0.128005

In [13]:
df.groupby("is_fraud")["amount"].mean()

is_fraud
0     92.047068
1    111.843986
Name: amount, dtype: float64

In [14]:
df["fraud_probability"].describe()

count    20000.000000
mean         0.387228
std          0.259322
min          0.011389
25%          0.179842
50%          0.337692
75%          0.539364
max          0.950000
Name: fraud_probability, dtype: float64

In [15]:
df["is_fraud"].value_counts()

is_fraud
0    12166
1     7834
Name: count, dtype: int64

In [16]:
df.groupby("is_fraud")["amount"].mean()

is_fraud
0     92.047068
1    111.843986
Name: amount, dtype: float64